import { getSession } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { redirect } from 'next/navigation';

export default async function RecordsPage({ searchParams }: { searchParams: { q?: string, status?: string } }) {
  const session = await getSession();
  if (!session) redirect('/');

  const where: any = {};
  if (searchParams.q) {
    where.OR = [
      { payload: { contains: searchParams.q } },
      { deviceFingerprint: { contains: searchParams.q } }
    ];
  }
  if (searchParams.status) {
    where.status = searchParams.status;
  }

  const licenses = await prisma.license.findMany({
    where,
    orderBy: { id: 'desc' },
    include: { application: true, generatedBy: true },
    take: 100
  });

  return (
    <div>
      <h2>LICENSE RECORDS</h2>
      
      <div className="card">
        <form method="GET" className="flex flex-col sm:flex-row gap-4 items-end">
          <div className="flex-[2] w-full">
            <label className="block text-accent mb-1">Search</label>
            <input type="text" name="q" className="input-field" placeholder="Code or Device ID" defaultValue={searchParams.q || ''} />
          </div>
          <div className="flex-1 w-full">
            <label className="block text-accent mb-1">Status</label>
            <select name="status" className="input-field" defaultValue={searchParams.status || ''}>
              <option value="">All</option>
              <option value="Active">Active</option>
              <option value="Trial">Trial</option>
              <option value="Suspended">Suspended</option>
              <option value="Revoked">Revoked</option>
            </select>
          </div>
          <button type="submit" className="btn w-full sm:w-auto">FILTER</button>
        </form>
      </div>

      <div className="overflow-x-auto">
        <table className="table-main">
          <thead>
            <tr>
              <th>Code</th>
              <th>Application</th>
              <th>Device ID</th>
              <th>Expiry</th>
              <th>Status</th>
              <th>Generated By</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {licenses.map(l => (
              <tr key={l.id}>
                <td>{l.payload}</td>
                <td>{l.application.name}</td>
                <td title={l.deviceFingerprint}>{l.deviceFingerprint.substring(0, 16)}...</td>
                <td>{new Date(l.expiryDate).toLocaleDateString()}</td>
                <td className={l.status === 'Active' ? 'text-success' : l.status === 'Revoked' ? 'text-error' : ''}>{l.status}</td>
                <td>{l.generatedBy?.username || 'System'}</td>
                <td>
                  <form method="POST" action="/api/licenses" className="inline flex gap-2">
                    <input type="hidden" name="id" value={l.id} />
                    {l.status === 'Active' && (
                      <>
                        <button type="submit" name="action" value="suspend" className="text-xs border px-2 py-1">Suspend</button>
                        <button type="submit" name="action" value="revoke" className="text-error border-error text-xs border px-2 py-1">Revoke</button>
                      </>
                    )}
                  </form>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
